canvas-medical/documentation

- _data/menus.yml
- collections/_sdk/caching.md
[KOALA-2856](https://canvasmedical.atlassian.net/browse/KOALA-2856)
[KOALA-2856]: https://canvasmedical.atlassian.net/browse/KOALA-2856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SDK Caching API documentation

- collections/_guides/your-first-application.md
https://canvasmedical.atlassian.net/browse/KOALA-2798
> feat: improve plugins applications

- _data/menus.yml
- _includes/toc.html
- collections/_sdk/handlers/simple-api.md
- collections/_sdk/handlers/simple-api/api.md
- collections/_sdk/handlers/simple-api/websocket.md
[KOALA-2862](https://canvasmedical.atlassian.net/browse/KOALA-2862)
[KOALA-2862]: https://canvasmedical.atlassian.net/browse/KOALA-2862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: websocket API

- collections/_sdk/events.md
https://canvasmedical.atlassian.net/browse/KOALA-2576
> update event documentation to include user context

- collections/_sdk/data/staff.md
https://canvasmedical.atlassian.net/browse/KOALA-2871
> Document StaffAddress and StaffPhoto models

- collections/_sdk/effects/create_form.md
This PR adds a link to the guide to the related effect page.
> add imports and link to patient metadata guide to effect page

- _data/menus.yml
- collections/_sdk/effects/patient-metadata.md
https://canvasmedical.atlassian.net/browse/KOALA-2911
> add documentation for patient metadata effect

- collections/_guides/embedding-a-smart-on-fhir-application.md
These were 2 steps that tripped me up going through the FHIR guide that we can potentially make more explicit.
The parts I updated:
> feat: add some gotchas from the FHIR guide

- collections/_sdk/effects/patient.md
https://canvasmedical.atlassian.net/browse/KOALA-2955
> feat: add patient external id to patient create effect

- collections/_sdk/data/condition.md
documents the change made here:
https://github.com/canvas-medical/canvas-plugins/pull/714
> feat: Add surgical field to Condition attributes table in documentation" (KOALA-3001)

- collections/_sdk/commands.md
- collections/_sdk/utils.md
Document where the code expected by `fdb_code` and `new_fdb_code` can be obtained.
> document `fdb_code` and `new_fdb_code`

- collections/_api/patient.md
- pages/upcoming-changes.md
https://canvasmedical.atlassian.net/browse/KOALA-3111
> Added breaking change notice for patient deceasedBoolean

- collections/_sdk/events.md
[Linked ticket](https://canvasmedical.atlassian.net/browse/KOALA-3048)
> docs: add patientmetadata events information

- collections/_sdk/commands.md
[KOALA-3072](https://canvasmedical.atlassian.net/browse/KOALA-3072)
[KOALA-2849]: https://canvasmedical.atlassian.net/browse/KOALA-2849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KOALA-3072]: https://canvasmedical.atlassian.net/browse/KOALA-3072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: immunization statement command docs

- _data/menus.yml
- collections/_sdk/data/charge_description_master.md
- collections/_sdk/data/payor_specific_charge.md
https://canvasmedical.atlassian.net/browse/KOALA-3028
> Add documentation for charge description master

- collections/_sdk/events.md
https://canvasmedical.atlassian.net/browse/KOALA-2910
> create documentation for new staff events

- collections/_guides/embedding-a-smart-on-fhir-application.md
https://canvasmedical.atlassian.net/browse/KOALA-2825
> Updated SMART App Launch example

- collections/_sdk/commands.md
supervising_provider_id is optional
> prescribe command: set required to false and fix typo

- collections/_sdk/canvas_cli.md
- collections/_sdk/secrets.md
[KOALA-3034](https://canvasmedical.atlassian.net/browse/KOALA-3034)
[KOALA-3034]: https://canvasmedical.atlassian.net/browse/KOALA-3034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add documentation for managing secrets via cli

- collections/_api/patient.md
https://canvasmedical.atlassian.net/browse/KOALA-3086
**Related PRs:**
* home-app: https://github.com/canvas-medical/canvas/pull/17927
* Fumage: https://github.com/canvas-medical/fumage/pull/805
* Bruno: https://github.com/canvas-medical/canvas-fhir-example-requests/pull/3
> New Patient FHIR extensions for tribal affiliation and sex

- collections/_sdk/testing-utils.md
fix the internal link on testing page and match to header
> Update testing-utils.md for clarity on testing tools

- collections/_api/practitioner.md
https://canvasmedical.atlassian.net/browse/PANDA-369
> PANDA:369: FHIR Practitioner - Update based on staff license revamp

- collections/_sdk/canvas_cli.md
- collections/_sdk/testing-utils.md
- **fix uv invocation**
- **quote for zsh users**
- **document how to upgrade and pip/uv difference**
> Fix UV invocation

- collections/_sdk/data/goal.md
https://canvasmedical.atlassian.net/browse/KOALA-3053
> create documentation for data module goal

- collections/_sdk/handlers/applications.md
[KOALA-3256](https://canvasmedical.atlassian.net/browse/KOALA-3256)
[KOALA-3256]: https://canvasmedical.atlassian.net/browse/KOALA-3256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: add context to application documentation

- _data/menus.yml
- collections/_sdk/data/assessment.md
- collections/_sdk/data/medication.md
- collections/_sdk/data/medication_statement.md
- collections/_sdk/data/stop_medication_event.md
https://canvasmedical.atlassian.net/browse/KOALA-2925
> add documentation for stop medication event and medication statement

- collections/_release-notes/2025-09-26-1-225-0.md
This release note details the afternoon update on 09.26.2025, including changes to form inactivation logic and the introduction of a beta questionnaire builder.
> Release 1.225.0

- _data/menus.yml
- collections/_sdk/effects/send_contact_verification.md
https://canvasmedical.atlassian.net/browse/KOALA-3301
> create documentation for send contact verification effect

- collections/_sdk/handlers/applications.md
https://canvasmedical.atlassian.net/browse/KOALA-3155
> update Applications documentation for multiple returned effects
